schema_version: 1

context:
  version: "0.8.1"

package:
  name: agent-client-protocol
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/a/agent-client-protocol/agent_client_protocol-${{ version }}.tar.gz
    sha256: 1bbf15663bf51f64942597f638e32a6284c5da918055d9672d3510e965143dbd

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - python ${{ python_min }}.*
    - pdm-backend
    - pip
  run:
    - python >=${{ python_min }}
    - pydantic >=2.7

tests:
  - python:
      imports:
        - acp
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/agentclientprotocol/python-sdk
  summary: A Python implement of Agent Client Protocol (ACP, by Zed Industries).

extra:
  recipe-maintainers:
    - davidbrochart
